BASE_DOMAIN_URL = "https://www.saucedemo.com/"
USER_NAME_XPATH = "//*[@id='user-name']"
PASSWORD_XPATH = "//*[@id='password']"
LOGIN_BTN_XPATH ="//*[@id='login-button']"
ERROR_MESSAGE_XPATH = "//*[@id='login_button_container']/div/form/div[3]/h3"
PRODUCT_COUNT_CLASS_NAME = "//*[@class='inventory_item']"
ADD_TO_CART_XPATH = "//*[@id='add-to-cart-sauce-labs-backpack']"
REMOVE_BTN = "//*[@id='remove-sauce-labs-backpack']"
BASKET_COUNT_XPATH = "//*[@class='shopping_cart_badge']"